// Generated by CoffeeScript 1.12.4
(function() {
  var appId, factService, mathQuery, replaceP, rp;

  rp = require('request-promise');

  appId = 'PEH42J-2UXG6GHW2L';

  replaceP = function(utt) {
    return utt.replace(/%/, ' percent');
  };

  mathQuery = function(utt) {
    var foo;
    return foo = replaceP(utt);
  };


  /*
  options =
    url: "http://api.wolframalpha.com/v1/result"
    qs:
      access_token: appId
      i:mathQuery
   */

  factService = function(utt) {
    var options;
    options = {
      url: "http://api.wolframalpha.com/v1/result?appid=" + appId + "&i=" + (mathQuery(utt))
    };
    return rp(options).then(function(resp) {
      return resp;
    })["catch"](function(err) {
      return "Sorry, that didn't make sense!";
    });

    /*  success = true
      if success
        resolve resp
      else
        reject Error, err
     */
  };

  module.exports = factService;


  /*
  module.exports =
    short: (utter) ->
      utt = utter
      mathService(utt)
        .then (resp) ->
          console.log resp
          Promise.resolve(resp)
   */

}).call(this);

//# sourceMappingURL=mathService.js.map
