// Generated by CoffeeScript 1.12.4
(function() {
  var Acuity, moment;

  moment = require('moment');

  Acuity = require('acuityscheduling');

  module.exports = {
    get: function(auth) {
      var acuity;
      acuity = Acuity.basic(auth);
      return new Promise(function(resolve, reject) {
        return acuity.request('appointment-types', function(err, response, appointmentTypes) {
          var d, data, i, len, success;
          data = [];
          for (i = 0, len = appointmentTypes.length; i < len; i++) {
            d = appointmentTypes[i];
            data.push({
              name: d.name,
              id: d.id,
              desc: d.description === '' ? 'none' : d.description,
              category: d.category === '' ? 'none' : d.category,
              type: d.type,
              price: d.price === '' ? 'free' : d.price,
              duration: d.duration,
              calId: d.calendarIDs
            });
          }
          success = true;
          if (success) {
            return resolve(data);
          } else {
            return reject(Error('fuck'));
          }
        });
      });
    }
  };


  /*auth =
    userId: 13277271,
    apiKey: '3d97f0676ab38e48d902d8c7cd138855'
  console.log getTypes(auth).then (data) -> console.log data
   */

}).call(this);

//# sourceMappingURL=apptTypesService.js.map
