// Generated by CoffeeScript 1.12.4
(function() {
  var Acuity, acuity, dates, getDates, moment;

  moment = require('moment');

  Acuity = require('acuityscheduling');

  acuity = Acuity.basic({
    userId: 13277271,
    apiKey: '3d97f0676ab38e48d902d8c7cd138855'
  });

  dates = dates != null ? dates : this;

  getDates = function(cb) {
    cb = cb || function() {};
    return acuity.request('availability', function(err, response, availability) {
      var parsedResults, results;
      results = JSON.stringify(availability);
      return parsedResults = JSON.parse(results);
    });
  };

}).call(this);

//# sourceMappingURL=availabilityService.js.map
