// Generated by CoffeeScript 1.12.5
(function() {
  var Acuity, helper;

  helper = require('./helperService');

  Acuity = require('acuityscheduling');


  /*BitLy = require 'bit.ly'
  bl = new BitLy('o_5tcob5i86o', 'R_8e3149a50a53ae4adeaf1a0385653d34')
   */

  module.exports = {
    createAppt: function(auth, options) {
      var acuity, opts;
      acuity = Acuity.basic(auth);
      opts = {
        method: 'POST',
        body: {
          appointmentTypeID: options.appointmentTypeID,
          datetime: helper.adjustOffset(options.date, options.timezone),
          firstName: options.firstName,
          lastName: options.lastName,
          email: options.email,
          phone: options.phone,
          timezone: options.timezone
        }
      };
      console.log(opts);
      return new Promise(function(resolve, reject) {
        return acuity.request("appointments", opts, function(err, res, appt) {
          var success;
          if (appt.error === 'no_available_calendar') {
            appt = 'not_avail';
          } else {
            appt = appt;
          }
          console.log(appt);
          success = true;
          if (success) {
            return resolve(appt);
          } else {
            reject(Error, err);
            return console.log(err);
          }
        });
      });
    }
  };

}).call(this);

//# sourceMappingURL=bookApptService.js.map
