// Generated by CoffeeScript 1.12.4

/*


moment = require 'moment'


Acuity = require 'acuityscheduling'

module.exports =


  getAll: (auth, options) ->

    @email = options.email
    @now = moment()

    if @email is 'foo' then ->

      acuity.request "appointments"
 */

(function() {


}).call(this);

//# sourceMappingURL=getAppointmentsService.js.map
