// Generated by CoffeeScript 1.12.4
(function() {
  var moment;

  moment = require('moment');

  moment.tz = require('moment-timezone');

  module.exports = {
    adjustOffset: function(date, tz) {
      this.date = moment(date).format();
      this.tz = tz;
      return this.datefix = moment(this.date).tz(this.tz).format();
    }
  };

}).call(this);

//# sourceMappingURL=helperService.js.map
