// Generated by CoffeeScript 1.12.4
(function() {
  var rp, token;

  token = '2a95f70536d539148c74c3b12c3b1f659316d740';

  rp = require('request-promise');

  module.exports = {
    short: function(url) {
      var options;
      options = {
        uri: 'https://api-ssl.bitly.com/v3/shorten',
        qs: {
          access_token: token,
          longUrl: url
        },
        json: true
      };
      return rp(options).then(function(response) {
        console.log(response);
        console.log(response.data.url);
        url = response.data.url;
        return url;
      })["catch"](function(err) {
        return console.log(err);
      });
    }
  };

}).call(this);

//# sourceMappingURL=shortLink.js.map
