// Generated by CoffeeScript 1.12.4
(function() {
  module.exports = {
    set: function(req, res) {
      return res.send({
        fname: req.query.fname,
        lname: req.query.lname
      });
    }
  };

}).call(this);

//# sourceMappingURL=FbNameController.js.map
