// Generated by CoffeeScript 1.12.4
(function() {
  module.exports = {
    getTypes: function(req, res) {
      return res.json({
        todo: 'getTypes() is not implemented yet!'
      });
    }
  };

}).call(this);

//# sourceMappingURL=GetAppointmentsController.js.map
