// Generated by CoffeeScript 1.12.4

/*
  * FbName.coffee
  *
  * @description :: TODO: You might write a short summary of how this model works and what it represents here.
  * @docs        :: http://sailsjs.org/documentation/concepts/models-and-orm/models

module.exports =

  attributes:

    set:
    type: 'string'
 */

(function() {


}).call(this);

//# sourceMappingURL=FbName.js.map
