// Generated by CoffeeScript 1.12.4

/*


module.exports =

  attributes:
    response:
      type: 'string'

    continue:
      type: 'boolean'
      defaultsTo: true

    customPayload:
      type: 'string'
      defaultsTo: ''

    quickReplies:
      type: 'array'

    cards:
      type: 'array'
      defaultsTo: null
 */

(function() {


}).call(this);

//# sourceMappingURL=responseJSON.js.map
